#ifndef MW_KOTO_UNDEF_MACROS_HPP
#define MW_KOTO_UNDEF_MACROS_HPP

#undef KOTO_DEFAULT_ENCODING
#undef KOTO_DEFAULT_CHAR_TYPE
#undef KOTO_DISABLE_CPP11
#undef KOTO_USE_CPP11
#undef KOTO_STATIC_ASSERT

#endif
